# Generated by Django 2.1.8 on 2019-06-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity', models.FloatField()),
                ('director', models.TextField()),
                ('imdb_score', models.FloatField()),
                ('name', models.TextField()),
                ('genre', models.ManyToManyField(to='movie.Genre')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
